### ISSUE TITLE
现在还能用吗？我多次尝试都没能成功，不知道怎么回事？

### ISSUE THREAD

**Issue by 1683728221** [cxjava/AutoChange12306CDN#2]
我是windows10系统环境的，pem证书转换导入过，但还是不成功；另外，我也在学习go中间人抓包，方便指教一下吗？

**Comment by cxjava** [comment]
@1683728221 看看是不是查询接口的地址变了？

确实比较久没有更新了。

**Comment by 1683728221** [comment]
应该是你证书失效了，我在浏览器看到证书显示是无效两个字，方便透露证书是怎么生成的吗，我自己试过好几次，不知道哪里细节出错了

**Comment by cxjava** [comment]
@1683728221 证书就是用openssl生成的，网上有相应的命令。

**Comment by liang306** [comment]
gscan.exe运行好像没反应

**Comment by cxjava** [comment]
> gscan.exe运行好像没反应

@liang306 具体错误是什么？命令行运行看看？会有详细日志的。
